theme: jekyll-theme-minimal
title: Drew Cunningham
description: What can the fitness of things mean, if not their fitness to a man's expectations? â€”George Eliot, Middlemarch
logo: /assets/profileimage3.jpg
is\_project\_page: false
